ALTER TABLE dbo.QuotationHeaders ALTER COLUMN VatType NVARCHAR(20) NOT NULL;
ALTER TABLE dbo.InvoiceHeaders ALTER COLUMN VatType NVARCHAR(20) NOT NULL;
ALTER TABLE dbo.CashSaleHeaders ALTER COLUMN VatType NVARCHAR(20) NOT NULL;
ALTER TABLE dbo.PurchaseOrderHeaders ALTER COLUMN VatType NVARCHAR(20) NOT NULL;
